### ISSUE TITLE
about LA?

### ISSUE THREAD

**Issue by ZHUXUHAN** [MCG-NJU/Structured-Sparse-RCNN#1]

**Comment by ZHUXUHAN** [comment]
hi, thanks for your outstanding work.
Where is the specific code about LA?
How to set parameters during testing?

**Comment by tyshiwo1** [comment]
1. Please refer to: https://github.com/MCG-NJU/Structured-Sparse-RCNN/blob/main/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py#L984

2. The temperature factor $\tau$ is a hyper-parameter. You can refer to our supplementary for its selection detail.
