### ISSUE TITLE
problem of reproducing training process

### ISSUE THREAD

**Issue by wishforgood** [MCG-NJU/Structured-Sparse-RCNN#2]
**What I expect:**

Train the model from scratch as instructed in readme.

**What I did:**

I prepared the dataset as instructed in [Scene-Graph-Benchmark.pytorch](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch), including preparing images and the labels.

I run the following command as instructed in readme (without distributed mode because I only use one GPU):

`python tools/relation_train_net.py --config-file "configs/simrel_e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX False MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False MODEL.ROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE none MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE sum MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER motifs SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 8 SOLVER.VAL_PERIOD 12000 SOLVER.MAX_ITER 80000 SOLVER.STEPS '(47000, 64000)' SOLVER.BASE_LR 0.000008 SOLVER.OPTIMIZER "ADAMW" MODEL.PRETRAINED_DETECTOR_CKPT checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR Outputs/real025kl_newe2rposition_fullobjbranch_300q_smalldyconv_prequeryaug9_norel_hardlabel MODEL.ROI_BOX_HEAD.MLP_HEAD_DIM 1024 MODEL.SimrelRCNN.ENABLE_BG_OBJ False MODEL.SimrelRCNN.ENABLE_REL_X2Y True MODEL.SimrelRCNN.REL_DIM 256 MODEL.SimrelRCNN.NUM_PROPOSALS 300 MODEL.SimrelRCNN.NUM_HEADS 6 MODEL.SimrelRCNN.REL_STACK_NUM 6 MODEL.SimrelRCNN.TRIPLET_MASK_WEIGHT 1.0 MODEL.SimrelRCNN.FREEZE_BACKBONE True MODEL.SimrelRCNN.CROSS_OBJ_FEAT_FUSION False MODEL.SimrelRCNN.CLASS_WEIGHT 1.333 MODEL.SimrelRCNN.L1_WEIGHT 5.0 MODEL.SimrelRCNN.GIOU_WEIGHT 2.0 GLOVE_DIR '' MODEL.SimrelRCNN.ENABLE_FREQ False MODEL.SimrelRCNN.ENABLE_QUERY_REVERSE False MODEL.SimrelRCNN.USE_REFINE_OBJ_FEATURE True MODEL.SimrelRCNN.FREEZE_PUREE_OBJDET False MODEL.SimrelRCNN.PURE_ENT_NUM_PROPOSALS 100 MODEL.SimrelRCNN.ENABLE_MASK_BRANCH False MODEL.SimrelRCNN.KL_BRANCH_WEIGHT 0.25 MODEL.SimrelRCNN.ENABLE_KL_BRANCH True MODEL.SimrelRCNN.POSI_ENCODE_DIM 64 MODEL.SimrelRCNN.REL_CLASS_WEIGHT 1.334 MODEL.SimrelRCNN.PURE_ENT_CLASS_WEIGHT 2.0 MODEL.SimrelRCNN.PURE_ENT_GIOU_WEIGHT 2.0 MODEL.SimrelRCNN.PURE_ENT_L1_WEIGHT 5.0 MODEL.SimrelRCNN.AUXILIARY_BRANCH True MODEL.SimrelRCNN.AUXILIARY_BRANCH_SELECT_ENT_MAX_NUM 25 MODEL.SimrelRCNN.AUXILIARY_BRANCH_START 11 MODEL.SimrelRCNN.ENABLE_ENT_PROP True MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_ANALYSIS False MODEL.SimrelRCNN.USE_CROSS_RANK False MODEL.SimrelRCNN.DISABLE_KQ_FUSION_SELFATTEN False MODEL.SimrelRCNN.DIM_ENT_PRE_CLS 256 MODEL.SimrelRCNN.DIM_ENT_PRE_REG 256 MODEL.SimrelRCNN.ONE_REL_CONV True MODEL.SimrelRCNN.ENABLE_BATCH_REDUCTION True MODEL.SimrelRCNN.USE_HARD_LABEL_KLMATCH True MODEL.SimrelRCNN.DISABLE_OBJ2REL_LOSS True`

**What the problem is:**

The log first shows numerous cuda errors like:

`/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [46,0,0], thread: [127,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.`

Then some python errors:

`Traceback (most recent call last):`

`  File "/home/visionx/software/anaconda2/envs/pysgg2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context`

`    return func(*args, **kwargs)`

`  File "/home/visionx/data6T/xuezhi/Structured-Sparse-RCNN/maskrcnn_benchmark/modeling/roi_heads/simrel_head/loss_simrel.py", line 1156, in forward`

`    cost_class_s = cost_class_s[:, X]`

`RuntimeError: CUDA error: device-side assert triggered`

I observed that 'cost_class_s' is of dim (..., 100), the values in 'X' range from 0 to 99 normally, but for a certain instance, the range becomes 100 to 199.

**Comment by wishforgood** [comment]
It seems that subtract X and Y with X[0] (which may be 0, 100, 200, ...) makes the models training proceeds. But I wonder if there is any problem.

**Comment by tyshiwo1** [comment]
maybe you should change this part: "SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 8"
into "SOLVER.IMS_PER_BATCH 1 TEST.IMS_PER_BATCH 1" in this command?

**Comment by tyshiwo1** [comment]
It's quite weird because I perform individual matching between triplets and object pairs for each batch.
Does it work when changing "SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 8" to "SOLVER.IMS_PER_BATCH 1 TEST.IMS_PER_BATCH 1"?

**Comment by wishforgood** [comment]
Thanks for your quick answer.
But when I restart the training process, I met an error called:
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`
and am searching for the solution to it.

**Comment by tyshiwo1** [comment]
I am wondering how large your GPU memory is, because when training this model with 1 GPU and batchsize=8, it may require about 80G? When I train it with 8 2080ti, about 10G memory on each GPU is used.

**Comment by wishforgood** [comment]
I'm sorry I actually used a batch of 4 but forgot to mention it. I'm using a 3090 with 24G memory.

**Comment by tyshiwo1** [comment]
Does it work when batchsize=2 ? the setting of bs=4 seems also to be costly?

"SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 8" -> "SOLVER.IMS_PER_BATCH 2 TEST.IMS_PER_BATCH 1"

**Comment by wishforgood** [comment]
OK, "SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 8" -> "SOLVER.IMS_PER_BATCH 1 TEST.IMS_PER_BATCH 1" works.
But how to stop the training process safely? I had to fallback to an earlier version of my project to solve the 
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`
problem.
Setting of bs=4 seems OK because the 24G memory is almost fully used when training, but no OOM error is reported. But this is under the condition of subtracting X and Y with X[0] (which may be 0, 100, 200, ...)

**Comment by wishforgood** [comment]
Stopping the training process directly reproduces the error
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`
I had to fallback to my backup version of project again. I'm using a remote debugger for the project, the cause of the error may be related to it.

"SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 8" -> "SOLVER.IMS_PER_BATCH 2 TEST.IMS_PER_BATCH 1" is not working, The same error occurs:
`RuntimeError: CUDA error: device-side assert triggered`
So the cause is related to batch data processing. Could you provide some tips on making it possible to increase the batch size for a single GPU?

**Comment by tyshiwo1** [comment]
Ok.
I've found something that may cause the "index out of bound" problem.
https://github.com/MCG-NJU/Structured-Sparse-RCNN/blob/main/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py#L325

You can try this: “ X=X+sum_ent_psedo_label, Y=Y+sum_ent_psedo_label,” should be changed to " X=X, Y=Y,"


I am sorry for not having free GPU at hand and not considering each GPU may get batchsize more than 1.

**Comment by tyshiwo1** [comment]
As for "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)", I haven't met this problem before. But I search online and find it may also be caused by "index out of bound"?

https://blog.csdn.net/weixin_39323526/article/details/78199298

**Comment by wishforgood** [comment]
OK, the solution works, thanks very much for your help.

When I use the debugger mode instead of directly running the code, the error
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`
somewhat disappeared.

**Comment by tyshiwo1** [comment]
You are welcome

**Comment by wishforgood** [comment]
Hi, I have finished training the model using the suggested command for a 300 query Structured-Sparse-RCNN model without LA, whose recall and mean recall are reported as 25.8 32.7 36.9 6.1 8.4 10.0 in the paper. I have trained my model on a single GTX3090 with batch size = 4, and I have not changed the base learning rate because I think AdamW will handle it when the batch size does not change too much. Here are my testing results:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.039
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.070
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.037
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.020
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.033
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.050
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.232
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.335
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.391
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.158
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.323
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.462
2022-05-25 04:26:08,812 maskrcnn_benchmark INFO: 
====================================================================================================
Detection evaluation mAp=0.0702
====================================================================================================
SGG eval:     R @ 20: 0.2396;     R @ 50: 0.3094;     R @ 100: 0.3546;  for mode=sgdet, type=Recall(Main).
SGG eval:  ng-R @ 20: 0.2505;  ng-R @ 50: 0.3386;  ng-R @ 100: 0.4011;  for mode=sgdet, type=No Graph Constraint Recall(Main).
SGG eval:    zR @ 20: 0.0093;    zR @ 50: 0.0196;    zR @ 100: 0.0275;  for mode=sgdet, type=Zero Shot Recall.
SGG eval: ng-zR @ 20: 0.0141; ng-zR @ 50: 0.0285; ng-zR @ 100: 0.0474;  for mode=sgdet, type=No Graph Constraint Zero Shot Recall.
SGG eval:    mR @ 20: 0.0529;    mR @ 50: 0.0732;    mR @ 100: 0.0890;  for mode=sgdet, type=Mean Recall.
----------------------- Details ------------------------
(above:0.0451) (across:0.0000) (against:0.0000) (along:0.0000) (and:0.0118) (at:0.1468) (attached to:0.0003) (behind:0.2470) (belonging to:0.0000) (between:0.0000) (carrying:0.1596) (covered in:0.0518) (covering:0.0065) (eating:0.1460) (flying in:0.0000) (for:0.0365) (from:0.0000) (growing on:0.0000) (hanging from:0.0159) (has:0.4167) (holding:0.3932) (in:0.1512) (in front of:0.0566) (laying on:0.0225) (looking at:0.0481) (lying on:0.0102) (made of:0.0000) (mounted on:0.0000) (near:0.1763) (of:0.3124) (on:0.4026) (on back of:0.0000) (over:0.0419) (painted on:0.0000) (parked on:0.0112) (part of:0.0000) (playing:0.0000) (riding:0.2698) (says:0.0000) (sitting on:0.1393) (standing on:0.0095) (to:0.0000) (under:0.1646) (using:0.1879) (walking in:0.0000) (walking on:0.0121) (watching:0.0696) (wearing:0.6642) (wears:0.0000) (with:0.0219) 
--------------------------------------------------------
SGG eval: ng-mR @ 20: 0.0841; ng-mR @ 50: 0.1387; ng-mR @ 100: 0.1846;  for mode=sgdet, type=No Graph Constraint Mean Recall.
----------------------- Details ------------------------
(above:0.2494) (across:0.0000) (against:0.0081) (along:0.0092) (and:0.0552) (at:0.2299) (attached to:0.1322) (behind:0.2178) (belonging to:0.1631) (between:0.0035) (carrying:0.3240) (covered in:0.0274) (covering:0.0796) (eating:0.1647) (flying in:0.0000) (for:0.0939) (from:0.0000) (growing on:0.0000) (hanging from:0.1295) (has:0.4330) (holding:0.3991) (in:0.3001) (in front of:0.1590) (laying on:0.3547) (looking at:0.2217) (lying on:0.2374) (made of:0.0000) (mounted on:0.1344) (near:0.2215) (of:0.3852) (on:0.4220) (on back of:0.0355) (over:0.1091) (painted on:0.0158) (parked on:0.3868) (part of:0.0535) (playing:0.0000) (riding:0.5252) (says:0.0000) (sitting on:0.3407) (standing on:0.2583) (to:0.1373) (under:0.2253) (using:0.2843) (walking in:0.0951) (walking on:0.2160) (watching:0.0804) (wearing:0.6134) (wears:0.4541) (with:0.2422) 
--------------------------------------------------------
====================================================================================================
```
I have read the log in another issue and found out that my results are also a little worse while training the model. Does it have something to do with the batch size? Could you give some advice on improving it?

**Comment by wishforgood** [comment]
Here are my settings:
```
--config-file
"configs/simrel_e2e_relation_X_101_32_8_FPN_1x.yaml"
MODEL.ROI_RELATION_HEAD.USE_GT_BOX
False
MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL
False
MODEL.ROI_RELATION_HEAD.PREDICTOR
CausalAnalysisPredictor
MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE
none
MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE
sum
MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER
motifs
SOLVER.IMS_PER_BATCH
4
TEST.IMS_PER_BATCH
4
SOLVER.VAL_PERIOD
12000
SOLVER.MAX_ITER
80000
SOLVER.STEPS
(47000,64000)
SOLVER.BASE_LR
0.000008
SOLVER.OPTIMIZER
"ADAMW"
MODEL.PRETRAINED_DETECTOR_CKPT
checkpoints/pretrained_faster_rcnn/model_final.pth
OUTPUT_DIR
Outputs/real025kl_newe2rposition_fullobjbranch_300q_smalldyconv_prequeryaug9_norel_hardlabel_v2
MODEL.ROI_BOX_HEAD.MLP_HEAD_DIM
1024
MODEL.SimrelRCNN.ENABLE_BG_OBJ
False
MODEL.SimrelRCNN.ENABLE_REL_X2Y
True
MODEL.SimrelRCNN.REL_DIM
256
MODEL.SimrelRCNN.NUM_PROPOSALS
300
MODEL.SimrelRCNN.NUM_HEADS
6
MODEL.SimrelRCNN.REL_STACK_NUM
6
MODEL.SimrelRCNN.TRIPLET_MASK_WEIGHT
1.0
MODEL.SimrelRCNN.FREEZE_BACKBONE
True
MODEL.SimrelRCNN.CROSS_OBJ_FEAT_FUSION
False
MODEL.SimrelRCNN.CLASS_WEIGHT
1.333
MODEL.SimrelRCNN.L1_WEIGHT
5.0
MODEL.SimrelRCNN.GIOU_WEIGHT
2.0
GLOVE_DIR
''
MODEL.SimrelRCNN.ENABLE_FREQ
False
MODEL.SimrelRCNN.ENABLE_QUERY_REVERSE
False
MODEL.SimrelRCNN.USE_REFINE_OBJ_FEATURE
True
MODEL.SimrelRCNN.FREEZE_PUREE_OBJDET
False
MODEL.SimrelRCNN.PURE_ENT_NUM_PROPOSALS
100
MODEL.SimrelRCNN.ENABLE_MASK_BRANCH
False
MODEL.SimrelRCNN.KL_BRANCH_WEIGHT
0.25
MODEL.SimrelRCNN.ENABLE_KL_BRANCH
True
MODEL.SimrelRCNN.POSI_ENCODE_DIM
64
MODEL.SimrelRCNN.REL_CLASS_WEIGHT
1.334
MODEL.SimrelRCNN.PURE_ENT_CLASS_WEIGHT
2.0
MODEL.SimrelRCNN.PURE_ENT_GIOU_WEIGHT
2.0
MODEL.SimrelRCNN.PURE_ENT_L1_WEIGHT
5.0
MODEL.SimrelRCNN.AUXILIARY_BRANCH
True
MODEL.SimrelRCNN.AUXILIARY_BRANCH_SELECT_ENT_MAX_NUM
25
MODEL.SimrelRCNN.AUXILIARY_BRANCH_START
11
MODEL.SimrelRCNN.ENABLE_ENT_PROP
True
MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_ANALYSIS
False
MODEL.SimrelRCNN.USE_CROSS_RANK
False
MODEL.SimrelRCNN.DISABLE_KQ_FUSION_SELFATTEN
False
MODEL.SimrelRCNN.DIM_ENT_PRE_CLS
256
MODEL.SimrelRCNN.DIM_ENT_PRE_REG
256
MODEL.SimrelRCNN.ONE_REL_CONV
True
MODEL.SimrelRCNN.ENABLE_BATCH_REDUCTION
True
MODEL.SimrelRCNN.USE_HARD_LABEL_KLMATCH
True
MODEL.SimrelRCNN.DISABLE_OBJ2REL_LOSS
True
```

**Comment by tyshiwo1** [comment]
Batchsize may influence the performane: https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/issues/6#issuecomment-596589442

Besides, you decreased the batchsize while kept the total iteration quantity unchanged.
This actually equals to reduce the number of training samples, which may also cause an undesirable performance.
Therefore, when you have to start training with bs=4, at least you need to increase the number of iteration (SOLVER.MAX_ITER) and change the SOLVER.STEPS

**Comment by wishforgood** [comment]
Oh, I ignored this factor. I will have another try while doubling the SOLVER.MAX_ITER and SOLVER.STEPS to see if the situation changes.

**Comment by tyshiwo1** [comment]
OK, if you still get a poor performance, maybe bs=8 is necessary

**Comment by wishforgood** [comment]
I have finished another training and got a good performance which is only slightly worse than the reported, by doubling the max iter. It seems that the decreased batch size is not a crucial problem. At least the R@100 and mR@100 are good. Here are the results:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.041
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.074
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.040
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.021
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.037
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.052
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.240
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.349
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.405
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.169
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.337
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.481
2022-06-02 17:41:45,733 maskrcnn_benchmark INFO: 
====================================================================================================
Detection evaluation mAp=0.0740
====================================================================================================
SGG eval:     R @ 20: 0.2522;     R @ 50: 0.3244;     R @ 100: 0.3708;  for mode=sgdet, type=Recall(Main).
SGG eval:  ng-R @ 20: 0.2638;  ng-R @ 50: 0.3556;  ng-R @ 100: 0.4199;  for mode=sgdet, type=No Graph Constraint Recall(Main).
SGG eval:    zR @ 20: 0.0141;    zR @ 50: 0.0245;    zR @ 100: 0.0368;  for mode=sgdet, type=Zero Shot Recall.
SGG eval: ng-zR @ 20: 0.0188; ng-zR @ 50: 0.0339; ng-zR @ 100: 0.0575;  for mode=sgdet, type=No Graph Constraint Zero Shot Recall.
SGG eval:    mR @ 20: 0.0578;    mR @ 50: 0.0811;    mR @ 100: 0.0982;  for mode=sgdet, type=Mean Recall.
----------------------- Details ------------------------
(above:0.0770) (across:0.0159) (against:0.0161) (along:0.0000) (and:0.0355) (at:0.1637) (attached to:0.0000) (behind:0.2547) (belonging to:0.0000) (between:0.0069) (carrying:0.1738) (covered in:0.0375) (covering:0.0065) (eating:0.1450) (flying in:0.0000) (for:0.0187) (from:0.0000) (growing on:0.0000) (hanging from:0.0249) (has:0.4407) (holding:0.4000) (in:0.1630) (in front of:0.0775) (laying on:0.0315) (looking at:0.0744) (lying on:0.0000) (made of:0.0000) (mounted on:0.0000) (near:0.2041) (of:0.3355) (on:0.4180) (on back of:0.0000) (over:0.0397) (painted on:0.0000) (parked on:0.0324) (part of:0.0000) (playing:0.0000) (riding:0.3191) (says:0.0000) (sitting on:0.1631) (standing on:0.0259) (to:0.0000) (under:0.1735) (using:0.1804) (walking in:0.0235) (walking on:0.0541) (watching:0.0825) (wearing:0.6722) (wears:0.0000) (with:0.0224) 
--------------------------------------------------------
SGG eval: ng-mR @ 20: 0.0949; ng-mR @ 50: 0.1565; ng-mR @ 100: 0.2100;  for mode=sgdet, type=No Graph Constraint Mean Recall.
----------------------- Details ------------------------
(above:0.2879) (across:0.0238) (against:0.0887) (along:0.0092) (and:0.0937) (at:0.2613) (attached to:0.1632) (behind:0.2391) (belonging to:0.1994) (between:0.0160) (carrying:0.3584) (covered in:0.0351) (covering:0.1054) (eating:0.2188) (flying in:0.0000) (for:0.1212) (from:0.0000) (growing on:0.0043) (hanging from:0.1474) (has:0.4567) (holding:0.4141) (in:0.3210) (in front of:0.1837) (laying on:0.3680) (looking at:0.2600) (lying on:0.3125) (made of:0.0000) (mounted on:0.1271) (near:0.2524) (of:0.4136) (on:0.4362) (on back of:0.1123) (over:0.1335) (painted on:0.0585) (parked on:0.3698) (part of:0.1728) (playing:0.0455) (riding:0.5449) (says:0.0000) (sitting on:0.3755) (standing on:0.2970) (to:0.1441) (under:0.2390) (using:0.3249) (walking in:0.1000) (walking on:0.2116) (watching:0.1104) (wearing:0.6220) (wears:0.4590) (with:0.2588) 
--------------------------------------------------------
====================================================================================================
```
