### ISSUE TITLE
error when eval

### ISSUE THREAD

**Issue by ZHUXUHAN** [MCG-NJU/Structured-Sparse-RCNN#3]
File "/root/Structured-Sparse-RCNN/maskrcnn_benchmark/modeling/roi_heads/simrel_head/model_simrel.py", line 1163, in forward
    pro_max_cls_score, pro_cls_id = torch.max(class_logits, dim=-1)
UnboundLocalError: local variable 'class_logits' referenced before assignment

**Comment by tyshiwo1** [comment]
OK, this is because you want to use the object_embed.
However, we find this module is not helpful in our model, so deprecate it:
In the command of Readme, we set: GLOVE_DIR ''

**Comment by ZHUXUHAN** [comment]
> OK, this is because you want to use the object_embed.
> However, we find this module is not helpful in our model, so deprecate it:
> In the command of Readme, we set: GLOVE_DIR ''

ok thanks!

**Comment by tyshiwo1** [comment]
you are welcome
