### ISSUE TITLE
about detection results?

### ISSUE THREAD

**Issue by ZHUXUHAN** [MCG-NJU/Structured-Sparse-RCNN#4]
can you upload the detection pre-trained model and the eval ap value of it?

**Comment by tyshiwo1** [comment]
Are you referring to the faster-rcnn weight? It can be found in https://github.com/SHTUPLUS/PySGG and https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch.
I will update readme

**Comment by ZHUXUHAN** [comment]
> Are you referring to the faster-rcnn weight? It can be found in https://github.com/SHTUPLUS/PySGG and https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch. I will update readme

yes, i just mean this. When i eval the model 'la03_real025kl_newe2rposition_fullobjbranch_300q_smalldyconv_prequeryaug9_norel_hardlabel' on 5000 images of VG eval dataset, i just get the detection map is about 8.0, it is accurate? can your give me your detection result?

**Comment by ZHUXUHAN** [comment]
> > Are you referring to the faster-rcnn weight? It can be found in https://github.com/SHTUPLUS/PySGG and https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch. I will update readme
> 
> yes, i just mean this. When i eval the model 'la03_real025kl_newe2rposition_fullobjbranch_300q_smalldyconv_prequeryaug9_norel_hardlabel' on 5000 images of VG eval dataset, i just get the detection map is about 8.0, it is accurate? can your give me your detection result?

because my nvidia device is limited, so i just can eval the model on small scale eval datasets, so can you give the eval results on 5000 images of VG evaluaion dataset?

**Comment by tyshiwo1** [comment]
Oh I see. It is normal to see a low mAP.

Because our model is directly predicting the object pairs, the AP evaluator in CocoApi is actually not comparable it, so its mAP cannot be properly shown in log.txt. This mAP of objects is not useful for our paradigm.

If you want to find the exact mAP of individual object predictions from these predicted object pairs, you need to modify the codes of CocoApi.

I will update the readme.

**Comment by tyshiwo1** [comment]
[log.txt](https://github.com/MCG-NJU/Structured-Sparse-RCNN/files/8751968/log.txt)

This is a log of our model. Its performance is slightly poorer because of the noise.

**Comment by ZHUXUHAN** [comment]
> [log.txt](https://github.com/MCG-NJU/Structured-Sparse-RCNN/files/8751968/log.txt)
> 
> This is a log of our model. Its performance is slightly poorer because of the noise.

ok,  thank you very much, this is helpful for me. Thanks for your contribution to the community

**Comment by tyshiwo1** [comment]
you are welcome
