### ISSUE TITLE
About method: how to tell two objects in two triplet are the same object or not?

### ISSUE THREAD

**Issue by Charles-Xie** [MCG-NJU/Structured-Sparse-RCNN#5]
Hi, thanks for sharing your work!
I read your paper, and got a question about the formulation of triplet detection: how to tell two objects in two triplets are the same object or not?
For example, in Fig.1, "woman wearing shoe" and "woman wearing shirt" are referring to the same "woman", but the triplet detection formulation will predict the "woman" box twice for these 2 triplet. How to tell if these two "woman" boxes are actually the same one?
I'm not familiar with SGG task, but it seems this detail is important for evaluation.

**Comment by tyshiwo1** [comment]
Thank you.
Actually, if you want to identify whether two objects indicate the same one, you may require a post-processing algorithm that combines these two object predition into one (this process may also be called the duplicate removal), just like NMS.
However, the evaluation mechanism of SGG is built on the triplets which are the basic elements of scene graph, so the above algorithm is not included in our code when testing.

**Comment by Charles-Xie** [comment]
Thanks a lot for the clear and helpful answer. Just surprised that the evaluation of SGG is performed on triplets. Thank you.
