### ISSUE TITLE
Some questions about training 

### ISSUE THREAD

**Issue by Coco-wyc** [MCG-NJU/Structured-Sparse-RCNN#7]
Hi, thanks for your nice work !
--------------------------------------
When I tried to reproduce the results (4*3090(24G), 300queries, batch=8) with the commends
----------------------------------------------------------------------------------------------------------------------------
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --master_port 10020 --nproc_per_node=4 tools/relation_train_net.py --config-file "configs/simrel_e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX False MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False MODEL.ROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE none MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE sum MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER motifs SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 8 SOLVER.VAL_PERIOD 12000 SOLVER.MAX_ITER 80000 SOLVER.STEPS '(47000, 64000)' SOLVER.BASE_LR 0.000008 SOLVER.OPTIMIZER "ADAMW" MODEL.PRETRAINED_DETECTOR_CKPT checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR Outputs/real025kl_newe2rposition_fullobjbranch_300q_smalldyconv_prequeryaug9_norel_hardlabel MODEL.ROI_BOX_HEAD.MLP_HEAD_DIM 1024 MODEL.SimrelRCNN.ENABLE_BG_OBJ False MODEL.SimrelRCNN.ENABLE_REL_X2Y True MODEL.SimrelRCNN.REL_DIM 256 MODEL.SimrelRCNN.NUM_PROPOSALS 300 MODEL.SimrelRCNN.NUM_HEADS 6 MODEL.SimrelRCNN.REL_STACK_NUM 6 MODEL.SimrelRCNN.TRIPLET_MASK_WEIGHT 1.0 MODEL.SimrelRCNN.FREEZE_BACKBONE True MODEL.SimrelRCNN.CROSS_OBJ_FEAT_FUSION False MODEL.SimrelRCNN.CLASS_WEIGHT 1.333 MODEL.SimrelRCNN.L1_WEIGHT 5.0 MODEL.SimrelRCNN.GIOU_WEIGHT 2.0 GLOVE_DIR '' MODEL.SimrelRCNN.ENABLE_FREQ False MODEL.SimrelRCNN.ENABLE_QUERY_REVERSE False MODEL.SimrelRCNN.USE_REFINE_OBJ_FEATURE True MODEL.SimrelRCNN.FREEZE_PUREE_OBJDET False MODEL.SimrelRCNN.PURE_ENT_NUM_PROPOSALS 100 MODEL.SimrelRCNN.ENABLE_MASK_BRANCH False MODEL.SimrelRCNN.KL_BRANCH_WEIGHT 0.25 MODEL.SimrelRCNN.ENABLE_KL_BRANCH True MODEL.SimrelRCNN.POSI_ENCODE_DIM 64 MODEL.SimrelRCNN.REL_CLASS_WEIGHT 1.334 MODEL.SimrelRCNN.PURE_ENT_CLASS_WEIGHT 2.0 MODEL.SimrelRCNN.PURE_ENT_GIOU_WEIGHT 2.0 MODEL.SimrelRCNN.PURE_ENT_L1_WEIGHT 5.0 MODEL.SimrelRCNN.AUXILIARY_BRANCH True MODEL.SimrelRCNN.AUXILIARY_BRANCH_SELECT_ENT_MAX_NUM 25 MODEL.SimrelRCNN.AUXILIARY_BRANCH_START 11 MODEL.SimrelRCNN.ENABLE_ENT_PROP True MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_ANALYSIS False MODEL.SimrelRCNN.USE_CROSS_RANK False MODEL.SimrelRCNN.DISABLE_KQ_FUSION_SELFATTEN False MODEL.SimrelRCNN.DIM_ENT_PRE_CLS 256 MODEL.SimrelRCNN.DIM_ENT_PRE_REG 256 MODEL.SimrelRCNN.ONE_REL_CONV True MODEL.SimrelRCNN.ENABLE_BATCH_REDUCTION True MODEL.SimrelRCNN.USE_HARD_LABEL_KLMATCH True MODEL.SimrelRCNN.DISABLE_OBJ2REL_LOSS True
----------------------------------------------------------------------------------------------------------------------------
The training process always stop at **iter:7200** without any errors. The volatile GPU-util for 4 gpus are all 100% and the memory usages are normal.  T^T
(But when I use bs=4 (1 sample for every gpu), the problem goes away.  )
To fully utilize the four gpus, I think bs=8 is a better choice but I couldn't find a solution to the aforementioned problem. Could you help me figure  out that problem? Thanks a lot!
---------------------------------------------------------------------------------------------------------------------------
What I have tried:
Change num_workers from 4 to 1 to  0  ×

**Comment by Coco-wyc** [comment]
I change bs to 16 for test and the code stop at iter:3600, so  I guess the last batch of the first epoch doesn't match the num of GPUs. How can I change the sampler to deal with the problem?

**Comment by tyshiwo1** [comment]
Oh, I also encounter such problem when training our model:
"The training process always stop at a certain iteration without any errors, and GPU-util for gpus are all 100% and the memory usages are normal."

I found that the training bs cannot be set to 2 on each GPU, but I haven't found a solution but turn to use 8 GPU with bs=1 on each GPU.

**Comment by Coco-wyc** [comment]
Thanks for your quick answer! XD
BS = 4 is ok, but I still wanna try bs = 8 because of longer running time (have to double max_iter when bs = 4).
I'm not so familiar with SGG code framework, could you tell me which files control the sampler?
Thanks a lot ! ! !T^T

**Comment by tyshiwo1** [comment]
maybe these links?

https://github.com/MCG-NJU/Structured-Sparse-RCNN/blob/main/tools/detector_pretrain_net.py#L79

https://github.com/MCG-NJU/Structured-Sparse-RCNN/blob/e63f639609ecfb89c0360ed5c66b24a574082957/maskrcnn_benchmark/data/build.py#L134

**Comment by Coco-wyc** [comment]
Thanks a lot! 
Although I haven't solve that problem. T^T
